import type { NewsArticle } from './articles'

const published = 'Aug 28, 2026'

type CurrentArticle = Pick<NewsArticle, 'slug' | 'title' | 'excerpt' | 'category' | 'topics' | 'hero' | 'heroAlt' | 'keyFindings' | 'ourTake'> & {
  opening: string
  context: string
  analysis: string
  implications: string[]
  source: NonNullable<NewsArticle['sources']>[number]
  read?: string
}

function article(data: CurrentArticle): NewsArticle {
  return {
    slug: data.slug,
    title: data.title,
    excerpt: data.excerpt,
    category: data.category,
    topics: data.topics,
    hero: data.hero,
    heroAlt: data.heroAlt,
    read: data.read ?? '5 min read',
    ago: '1 day ago',
    published,
    author: 'DesignsWorkLife Editorial Desk',
    authorBio: 'The DesignsWorkLife editorial desk reviews public campaign material and industry reporting, then adds independent analysis for creative and marketing teams.',
    verificationStatus: 'source-reviewed',
    factChecked: 'Aug 30, 2026',
    sources: [data.source],
    heroCredit: 'Photo via Pixabay',
    body: [
      { type: 'p', text: data.opening },
      { type: 'p', text: data.context },
      { type: 'h2', text: 'What the work is really doing' },
      { type: 'p', text: data.analysis },
      { type: 'h2', text: 'What creative teams can carry forward' },
      { type: 'ul', items: data.implications },
    ],
    keyFindings: data.keyFindings,
    ourTake: data.ourTake,
    agencyCta: { label: 'Explore relevant agencies', to: '/agency/digital-marketing' },
  }
}

export const currentNewsArticles: NewsArticle[] = [
  article({
    slug: 'apple-mac-mini-m6-claymation-ai-performance',
    title: 'Apple Gives the Mac Mini M6 Real Clay Muscles to Make AI Performance Feel Tangible',
    excerpt: 'A handcrafted launch film turns processor claims into physical comedy, proving that an AI product story does not need AI-generated imagery to feel current.',
    category: 'Creative',
    topics: ['creative', 'tech', 'advertising', 'ai'],
    hero: '/designsworklife/images/pixabay/computer-768696_1280.jpg',
    heroAlt: 'Compact computer workstation with displays and creative software',
    opening: 'Apple introduced the Mac mini M6 with “The Mighty Mac Mini,” a claymation film that gives the small desktop an exaggerated bodybuilder physique. The visual joke is immediate: a compact box can carry far more power than its footprint suggests.',
    context: 'TBWA\\Media Arts Lab developed the campaign with Blinkink and Stoopid Buddy Stoodios. Director Nicos Livesey and the production team translated performance claims into handmade scenes, including a muscular figure, racing imagery, a mechanical brain, and a rocket-like burst of speed.',
    analysis: 'The craft choice is the strategy, not decoration. By emphasizing physical materials and visible imperfection, Apple gives viewers a sensory counterpoint to abstract AI benchmarks. The campaign also protects the product from the interchangeable glowing-interface language that now dominates technology advertising.',
    implications: ['Turn technical specifications into one visual metaphor a viewer can understand before reading the copy.', 'Use production craft to create contrast with the conventions of the category.', 'Let the product remain visually recognizable even while the surrounding world becomes playful.'],
    keyFindings: ['The film was produced as handcrafted claymation rather than generated with AI tools.', 'Physical comedy translates a compact-device performance claim into a memorable image.', 'A distinctive production method helps a familiar product launch earn cultural attention.'],
    ourTake: 'The smartest part of the campaign is its restraint: one small computer, one oversized-strength metaphor, and a material treatment that makes every frame recognizably its own.',
    source: { title: 'Apple Sells AI Muscle With Claymation in New Mac Mini M6 Ad', publisher: 'DesignRush', url: 'https://news.designrush.com/apple-mighty-mac-mini-m6-claymation-tbwa' },
  }),
  article({
    slug: 'evian-200-years-premium-brand-memory',
    title: 'At 200, evian Shows How Provenance Can Keep a Commodity Feeling Premium',
    excerpt: 'The water brand’s anniversary connects Alpine origin, recognizable packaging, and design collaborations into one long-running premium system.',
    category: 'Brands',
    topics: ['branding', 'marketing', 'creative'],
    hero: '/designsworklife/images/pixabay/road-1072823_1280.jpg',
    heroAlt: 'Natural landscape path surrounded by trees, representing origin and place',
    opening: 'evian is using its 200th anniversary to reinforce the story behind the bottle rather than simply celebrating longevity. The campaign returns to the brand’s Alpine origin and the long natural filtration journey that has anchored its positioning for generations.',
    context: 'The anniversary program extends the “Live Young” platform through a 200 Years Young message, special packaging, cultural partnerships, and a commemorative Jeff Koons bottle. Together, these elements turn history into evidence of consistency instead of nostalgia for its own sake.',
    analysis: 'Water offers very little functional space for differentiation, so the brand has built value around place, ritual, and design recognition. Its mountain provenance creates credibility, while collaborations keep the same origin story circulating through fashion, art, and sport.',
    implications: ['Treat origin stories as living brand assets that can support new formats without changing their core meaning.', 'Use limited packaging to make familiar identity elements newly noticeable.', 'Balance heritage with contemporary cultural partners so an anniversary looks forward as well as back.'],
    keyFindings: ['The anniversary keeps Alpine provenance at the center of the premium argument.', 'Designer collaborations give a routine purchase the behavior of a collectible object.', 'Long-term consistency can create pricing power when every touchpoint reinforces the same memory structures.'],
    ourTake: 'evian demonstrates that premium positioning is rarely created by a single campaign. It is accumulated through decades of disciplined repetition, refreshed just enough to remain culturally visible.',
    source: { title: '200 Years of evian: Why We Pay Premium for Bottled Water', publisher: 'DesignRush', url: 'https://news.designrush.com/evian-200-years-premium-bottled-water-branding' },
  }),
  article({
    slug: 'asics-good-vibrations-trail-running-campaign',
    title: 'ASICS Makes the Hard Part of Trail Running the Emotional Payoff',
    excerpt: '“Good Vibrations” avoids polished finish-line triumphs and focuses on the difficult terrain that makes the post-run feeling believable.',
    category: 'Marketing',
    topics: ['marketing', 'creative', 'advertising'],
    hero: '/designsworklife/images/pixabay/jogging-5863698_1280.jpg',
    heroAlt: 'Trail runner moving along a winding forest path',
    opening: 'ASICS and creative agency AGIT8 have launched “Good Vibrations,” a global trail-running campaign built around discomfort rather than effortless athletic perfection. Mud, steep climbs, unstable ground, and fatigue become the proof behind the emotional reward.',
    context: 'The work features elite trail runners including Tom Evans, Ben Dhiman, and Sara Alonso. Its distorted use of a familiar feel-good soundtrack creates tension between what the run looks like from the outside and how it feels once the effort begins to pay back.',
    analysis: 'Most performance campaigns hurry toward victory. This one spends time inside the unpleasant middle, where trail runners recognize themselves. That specificity makes the brand’s mind-and-body promise feel earned instead of applied as a slogan after the footage was shot.',
    implications: ['Show the friction that makes a product benefit credible, not only the polished result.', 'Use sound to challenge the image and create a more memorable emotional turn.', 'Build community relevance through details that experienced participants immediately recognize.'],
    keyFindings: ['The campaign frames physical difficulty as the route to mental reward.', 'Recognizable trail athletes strengthen credibility without replacing the central idea.', 'Category growth gives ASICS a timely reason to define what trail running feels like.'],
    ourTake: 'The work succeeds because it does not pretend exercise is always joyful. By admitting the effort, ASICS makes the eventual release more persuasive—and more human.',
    source: { title: "ASICS Chases the Runner's High as Trail Running Participation Hits 1.3 Million", publisher: 'DesignRush', url: 'https://news.designrush.com/asics-agit8-good-vibrations-trail-running-campaign' },
  }),
  article({
    slug: 'omnicom-hearts-united-media-network',
    title: 'Hearts United Turns Omnicom’s Media Consolidation Into a New Global Operating Brand',
    excerpt: 'The network combines Hearts & Science and Mediahub across 40 markets, aiming to connect data-led planning with stronger creative media thinking.',
    category: 'Agency',
    topics: ['agency', 'business', 'marketing'],
    hero: '/designsworklife/images/pixabay/meeting-2284501_1280.jpg',
    heroAlt: 'Team collaborating around plans and shared working documents',
    opening: 'Omnicom Media has introduced Hearts United, bringing Hearts & Science and Mediahub together under a global network spanning 40 markets. The launch gives a visible identity to a broader post-acquisition integration effort.',
    context: 'Nicole Estebanell will lead the U.S. operation, while Ross Jenkins takes responsibility for EMEA. Leadership for APAC and Latin America is expected to follow, making the rollout as much an organizational design challenge as a naming exercise.',
    analysis: 'The promise is complementary capability: Hearts & Science contributes data-centered planning and Mediahub brings a reputation for creative media execution. The real test will be whether shared systems improve decisions without flattening the cultures that made either agency valuable.',
    implications: ['Define the operating advantage of a merger in client outcomes, not only scale language.', 'Give regional leadership enough authority to adapt a global model to local media behavior.', 'Preserve specialist talent by making roles and decision rights visible early in the integration.'],
    keyFindings: ['The network joins two established agency brands across 40 markets.', 'Initial leadership covers the U.S. and EMEA, with more regions to follow.', 'Integration quality—not the announcement—will determine whether the combined offer feels differentiated.'],
    ourTake: 'A new network name can simplify the story for clients, but it cannot substitute for a clear way of working. Hearts United will be judged by how quickly combined capability becomes easier to buy and use.',
    source: { title: "Omnicom's Hearts United Launches With 2 Leadership Seats Open", publisher: 'DesignRush', url: 'https://news.designrush.com/omnicom-media-hearts-united-launch' },
  }),
  article({
    slug: 'olivia-rodrigo-taco-bell-baja-blast-pink',
    title: 'Taco Bell Turns Olivia Rodrigo’s Regular Order Into a Pink Baja Blast Moment',
    excerpt: 'A fan-known ordering habit becomes the bridge between a celebrity’s visual world and a limited drink people can actually try.',
    category: 'Brands',
    topics: ['branding', 'marketing', 'creative'],
    hero: '/designsworklife/images/pixabay/woman-1851464_1280.jpg',
    heroAlt: 'Young woman using a laptop beside a drink in a colorful lifestyle setting',
    opening: 'Taco Bell and Mountain Dew have developed a pink Baja Blast around Olivia Rodrigo’s familiar Taco Bell order. The tropical-lime base is paired with pink lemonade, turning an existing fan detail into a product collaboration rather than a conventional endorsement.',
    context: 'The launch connects with the pink visual language surrounding Rodrigo’s current era and extends into a live fan experience before a broader release. The product gives the partnership a simple action: order the drink, photograph it, and participate in the same visual world.',
    analysis: 'Celebrity collaborations often begin with reach and search backward for relevance. This one begins with a real behavior already discussed by fans. That makes the drink feel like an extension of an existing relationship instead of merchandise designed after the contract was signed.',
    implications: ['Start with a documented behavior or preference that audiences already associate with the talent.', 'Translate visual identity into the product itself so the collaboration remains recognizable without a portrait.', 'Design the activation around an action customers can repeat and share.'],
    keyFindings: ['The collaboration grows from Rodrigo’s known ordering habit.', 'Color links the beverage to the artist’s visual identity while keeping Baja Blast recognizable.', 'A physical product gives fandom a low-friction participation mechanic.'],
    ourTake: 'The strongest celebrity products feel discovered rather than assigned. Here, the order came first, which gives the campaign a small but valuable layer of authenticity.',
    source: { title: 'Olivia Rodrigo Turns Her Taco Bell Order Pink, With Baja Blast Along for the Ride', publisher: 'DesignRush', url: 'https://news.designrush.com/olivia-rodrigo-taco-bell-mountain-dew-baja-blast-pink-launch' },
  }),
  article({
    slug: 'original-data-content-marketing-citations',
    title: 'Original Data Is Becoming the Content Asset Search Systems Cannot Easily Replace',
    excerpt: 'As generic explainers multiply, proprietary statistics and transparent methodology give publishers a stronger reason to be cited, linked, and remembered.',
    category: 'Marketing',
    topics: ['marketing', 'tech', 'ai'],
    hero: '/designsworklife/images/pixabay/books-2596809_1280.jpg',
    heroAlt: 'Research library representing evidence, sources, and original knowledge',
    opening: 'Content teams are discovering that polished opinion is no longer scarce. Generative tools can produce a competent overview in seconds, which weakens the value of publishing another summary built from the same public material.',
    context: 'Original surveys, benchmarks, experiments, and aggregated first-party data create a different kind of asset. They supply facts other publishers can reference and give search and answer systems a specific source to attribute when a number matters.',
    analysis: 'Data only creates authority when readers can understand where it came from. Sample size, collection period, definitions, and limitations are part of the product. Without that transparency, a striking statistic may travel briefly but will not build durable trust.',
    implications: ['Design research around a real customer decision rather than collecting numbers for publicity alone.', 'Publish methodology beside the headline findings so citations remain defensible.', 'Build recurring benchmarks that can accumulate value and comparison over time.'],
    keyFindings: ['Generic summaries are easier for answer engines and competitors to reproduce.', 'Proprietary evidence gives other writers a concrete reason to cite the originating brand.', 'Transparent methodology is essential to turn attention into authority.'],
    ourTake: 'The next content advantage will come from owning useful evidence, not producing the largest volume of prose. A modest, well-designed dataset can outperform dozens of interchangeable articles.',
    source: { title: 'Why Statistics Outrank Opinions in 2026 Content Marketing', publisher: 'DesignRush', url: 'https://news.designrush.com/data-driven-content-marketing-statistics' },
  }),
  article({
    slug: 'banking-app-feature-overload-product-design',
    title: 'Banking Apps Are Learning That More Features Can Make Everyday Money Tasks Feel Harder',
    excerpt: 'Feature expansion looks impressive on a roadmap, but crowded navigation and competing prompts can erode confidence in the moments users need clarity most.',
    category: 'Technology',
    topics: ['tech', 'design', 'business'],
    hero: '/designsworklife/images/pixabay/hand-1850120_1280.jpg',
    heroAlt: 'Hand interacting with a digital interface, representing mobile product complexity',
    opening: 'Banking apps have expanded from balance checking and transfers into investing, subscriptions, rewards, credit monitoring, budgeting, and personalized offers. That breadth can increase utility, but it also raises the cost of finding the one action a customer needs right now.',
    context: 'Recent industry research highlighted widespread concern about feature overload. In financial products, the usability consequence is especially serious: ambiguity can make users hesitate, abandon a task, or worry that they have made an irreversible mistake.',
    analysis: 'The problem is not the number of capabilities by itself. It is the absence of hierarchy. A well-designed product can support deep functionality when primary tasks remain predictable and advanced tools appear progressively, in context, rather than competing on the home screen.',
    implications: ['Protect the fastest path to high-frequency tasks before adding new promotional surfaces.', 'Reveal advanced functions progressively instead of giving every feature equal visual weight.', 'Test comprehension and confidence alongside completion time and conversion.'],
    keyFindings: ['Breadth becomes a liability when navigation does not reflect real task frequency.', 'Financial interfaces must optimize for confidence as well as speed.', 'Progressive disclosure lets complex products grow without making every session feel complex.'],
    ourTake: 'Product teams should treat attention as a limited account balance. Every badge, card, and cross-sell spends some of it; the essential task must always have enough left to complete safely.',
    source: { title: '71.8% of Banking App Users Worry About Feature Overload', publisher: 'DesignRush', url: 'https://news.designrush.com/banking-app-feature-overload' },
  }),
]
